# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Build client tools (MSBuild)"

on:
  push:
    branches:
    - master

    paths:
      - '.github/workflows/build_msbuild_client_tools.yml'
      - 'ClientTools.slnx'

  pull_request:
    branches:
    - master

    paths:
      - '.github/workflows/build_msbuild_client_tools.yml'
      - 'ClientTools.slnx'
 
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref || github.run_id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# These should really be moved into the one solution.
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [Win32, x64]

    name: "Client tools: ${{ matrix.BUILD_CONFIGURATION }} - ${{ matrix.BUILD_PLATFORM }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build tools
      run: msbuild /m /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" ClientTools.slnx
